// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    final options = switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      TargetPlatform.windows => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      TargetPlatform.linux => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ),
      _ => throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      ),
    };

    _validate(options);
    return options;
  }

  static void _validate(FirebaseOptions options) {
    if (options.apiKey.isEmpty) {
      throw StateError(
        'Missing Firebase API key. Run Flutter with '
        '--dart-define-from-file=firebase.env.json or define the platform '
        'API key with --dart-define.',
      );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:939927765385:android:583aa4f47c6e5bbd026158',
    messagingSenderId: '939927765385',
    projectId: 'yarnstashmobileapp',
    storageBucket: 'yarnstashmobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:939927765385:ios:91bfa9462ac49251026158',
    messagingSenderId: '939927765385',
    projectId: 'yarnstashmobileapp',
    storageBucket: 'yarnstashmobileapp.firebasestorage.app',
    iosBundleId: 'com.yarnstash.yarnStash',
  );
}
